sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank021/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true shashank021/react-test npm test

after_success:
  - docker build -t shashank021/multi-client ./complex/client
  - docker build -t shashank021/multi-nginx ./complex/nginx
  - docker build -t shashank021/multi-server ./complex/server
  - docker build -t shashank021/multi-worker  ./complex/worker
  # Login to Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -p password-stdin
  # Push images to dockerhub
  - docker push shashank021/multi-client
  - docker push shashank021/multi-nginx
  - docker push shashank021/multi-server
  - docker push shashank021/multi-worker 

