sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank021/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shashank021/react-test npm test

after_success
  - docker build -t shashank021/multi-client ./client
  - docker build -t shashank021/multi-nginx ./nginx
  - docker build -t shashank021/multi-server ./server
  - docker build -t shashank021/multi-worker  ./worker
  # Login to Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -p password-stdin
  # Push images to dockerhub
  - docker push shashank021/multi-client
  - docker push shashank021/multi-nginx
  - docker push shashank021/multi-server
  - docker push shashank021/multi-worker 

